
/*******************************************************************************
  SCRIPT DSA
********************************************************************************/


/*******************************************************************************
   Create database
********************************************************************************/
CREATE USER C##ODS IDENTIFIED BY ODS123;

GRANT CONNECT, RESOURCE TO C##ODS;

ALTER USER C##ODS QUOTA UNLIMITED ON USERS;



/*******************************************************************************
   Create Tables
********************************************************************************/
CREATE TABLE C##ODS.ARTIST (
    ARTISTID NUMBER,
    NAME NVARCHAR2(120),
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);


CREATE TABLE C##ODS.ALBUM (
    ALBUMID NUMBER,
    TITLE NVARCHAR2(160),
    ARTISTID NUMBER,
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.GENRE (
    GENREID NUMBER,
    NAME NVARCHAR2(120),
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.MEDIATYPE (
    MEDIATYPEID NUMBER,
    NAME NVARCHAR2(120),
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.TRACK (
    TRACKID NUMBER,
    NAME NVARCHAR2(200),
    ALBUMID NUMBER,
    MEDIATYPEID NUMBER,
    GENREID NUMBER,
    COMPOSER NVARCHAR2(220),
    MILLISECONDS NUMBER,
    BYTES NUMBER,
    UNITPRICE NUMBER(10,2),
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.PLAYLIST (
    PLAYLISTID NUMBER,
    NAME NVARCHAR2(120),
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.PLAYLISTTRACK (
    PLAYLISTID NUMBER,
    TRACKID NUMBER,
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.EMPLOYEE (
    EMPLOYEEID NUMBER,
    LASTNAME NVARCHAR2(20),
    FIRSTNAME NVARCHAR2(20),
    TITLE NVARCHAR2(30),
    REPORTSTO NUMBER,
    BIRTHDATE DATE,
    HIREDATE DATE,
    ADDRESS NVARCHAR2(70),
    CITY NVARCHAR2(40),
    STATE NVARCHAR2(40),
    COUNTRY NVARCHAR2(40),
    POSTALCODE NVARCHAR2(10),
    PHONE NVARCHAR2(24),
    FAX NVARCHAR2(24),
    EMAIL NVARCHAR2(60),
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.CUSTOMER (
    CUSTOMERID NUMBER,
    FIRSTNAME NVARCHAR2(40),
    LASTNAME NVARCHAR2(20),
    COMPANY NVARCHAR2(80),
    ADDRESS NVARCHAR2(70),
    CITY NVARCHAR2(40),
    STATE NVARCHAR2(40),
    COUNTRY NVARCHAR2(40),
    POSTALCODE NVARCHAR2(10),
    PHONE NVARCHAR2(24),
    EMAIL NVARCHAR2(60),
    SUPPORTREPID NUMBER,
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.INVOICE (
    INVOICEID NUMBER,
    CUSTOMERID NUMBER,
    INVOICEDATE DATE,
    BILLINGADDRESS NVARCHAR2(70),
    BILLINGCITY NVARCHAR2(40),
    BILLINGSTATE NVARCHAR2(40),
    BILLINGCOUNTRY NVARCHAR2(40),
    BILLINGPOSTALCODE NVARCHAR2(10),
    TOTAL NUMBER(10,2),
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE C##ODS.INVOICELINE (
    INVOICELINEID NUMBER,
    INVOICEID NUMBER,
    TRACKID NUMBER,
    UNITPRICE NUMBER(10,2),
    QUANTITY NUMBER,
    INTEGRATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);
